### ISSUE TITLE
No ECS API calls

### ISSUE THREAD

**Issue by jeremykeen** [seethedata/easycode#1]
My issue is that there are no ECS API calls anywhere in your code.

**Comment by cghiorzi** [comment]
Thank you for your feedback. We are waiting for SanDisk USB thumbdrive support within ECS before coding the integration.

**Comment by jeremykeen** [comment]
Attach them to docker hosts and your wish will be fulfilled. Seriously, let's do it just for fun.

**Comment by cghiorzi** [comment]
It was quite impressive how quickly you were able to propose a workable solution. Yet another example of how valuable EMC technical resources are.

**Comment by jeremykeen** [comment]
CoprHD handles all of my storage responses near instantaneously.
